### ISSUE TITLE
Not compatible yet with purs 0.11.6 it seems?

### ISSUE THREAD

**Issue by metaleap** [purescript-contrib/purescript-http-methods#3]
Using `purs` current `master` branch (prints `--version` as `0.11.6 dev build`), attempting to `pulp build` a project with `purescript-http-methods` (got version 3.0.0 from Pursuit) in the deps results in:

    * Building project in /home/rox/c/ps/test-pscorefn-src
    Compiling Data.HTTP.Method
    Error found:
    at bower_components/purescript-http-methods/src/Data/HTTP/Method.purs line 40, column 8 - line 40, column 48
    
      Cannot derive a type class instance for
                                           
        Data.Generic.Generic Method
                                           
      since instances of this type class are not derivable.

**Comment by garyb** [comment]
Thanks for opening these issues, but it's not really necessary to do for any further you encounter :wink:

There will be a full round of breaking changes that go with the 0.11 release, so all libraries will need updating anyway.

**Comment by metaleap** [comment]
Haha I'm through now. Most libs had no issues anyway. Well, now it's already in the appropriate to-dos  =)
